### ISSUE TITLE
meters instead of metres

### ISSUE THREAD

**Issue by espinielli** [hypertidy/geodist#29]
I saw #28... Maybe the spelling should be 'meter'.
I was not sure so I checked and found this:
https://www.nist.gov/pml/weights-and-measures/metric-si/si-units

**Comment by espinielli** [comment]
(I would have loved to propose a PR...but I am on my phone bringing the kids to bed 😄

**Comment by mpadge** [comment]
Thanks @espinielli for always keeping a keen eye on things :wink:. In this case, I'm going to respectively close this one, because "meter" is US-spelling only, while "metre" is both [international standard](https://en.wikipedia.org/wiki/International_System_of_Units), and my native form of English (:australia: in my case).
