### ISSUE TITLE
Rendered doc is stale 

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/geodist#40]
Pre 0.1.0 here: https://hypertidy.github.io/geodist/

**Comment by kadyb** [comment]
@mpadge, I think the problem is that the two directories that contain the website are mixed ([index.html ](https://github.com/hypertidy/geodist/blob/gh-pages/index.html) hasn't been updated in 3 years; but it has been updated in the `docs` directory). Maybe you should delete `gh-pages` branch and regenerate?

**Comment by mdsumner** [comment]
Yes, that wasn't the fix, I should have been more explicit:

![Screenshot_20241125-100222](https://github.com/user-attachments/assets/c2f5c809-6e82-4862-8dcd-dc360d4441dc)



There's no geodist_min in the Reference

**Comment by mpadge** [comment]
Ah, thanks @kadyb and @mdsumner. Re-opening to properly fix ...

**Comment by mpadge** [comment]
Geez, that was more commits that it shoulda been. So the workflow needs to  have `folder: docs`, which then renders all docs *not* in the `/docs` folder, but in the root directory. Putting `folder: .` in the workflow file dumps the whole repo in the root, with the pkgdown site then rendered in the docs. So `folder` is *not* where the site is rendered, but where it is taken from. Setting to `docs` *takes* the files from there and puts then in `.`. And so that then needs to be the setting in the "pages" bit of the repo. Way more confusing than it oughta be, I'd say.
